### ISSUE TITLE
Proposal: make providing multiple values to options possible

### ISSUE THREAD

**Issue by joachimschmidt557** [Hejsil/zig-clap#20]
This would enable commands such as

```shell
$ zig-cli-program --enable=abc --enable=asdf
```

Currently, only one value can be provided to an option. If accepted, I can look into implementing this.

**Comment by Hejsil** [comment]
Hmm, currently we have `args.option("--flag")` returning an `?[]const u8`, which is quite convenient for most programs. I would be reluctant to change this API. I'm going to propose two ways you can get something in the vain of what you want, and then we can talk further if these are not adequate:
* Use a comma separated list instead of separate args:
   * `--enable=abc,asdf`
* Use the `StreamingClap` instead of `clap.parse`

**Comment by joachimschmidt557** [comment]
Ok, I'll guess I'll try out `StreamingClap` first. It seems more flexible and maybe more suitable for my use case.
